### ISSUE TITLE
Write the code of conduct

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/opendesign#1]
Write a code of conduct (COC)

There should be a COC for:

1 - The Open Design repo & contributing to it (this repo)
2 - The events, attending and what we expect
3 - The TenFour repo (https://github.com/ushahidi/tenfour) that is linked to the Open Design repo. But because this repo could attract dev involvement too.

Our COC needs to be design-focused and also intersectionally inclusive.

**Comment by vbhv** [comment]
@Erioldoesdesign is the code of conduct meant for the community (designers, orgs) participating and is it both for the website as well as events? Maybe we can focus on website as a start?

**Comment by Erioldoesdesign** [comment]
@vbhv There should be a COC for events & online/repo contribution. 

Please do start on the repo/website first and we can look at one for an event later :)

**Comment by vbhv** [comment]
Found two current COCs. One for community participant and the other for open source contributor profile.
https://community-covenant.net/
https://www.contributor-covenant.org/


Other COC examples:
https://indieweb.org/code-of-conduct-examples
http://web.archive.org/web/20141109123859/http://speakup.io/coc.html
https://www.djangoproject.com/conduct/
https://opensource.guide/code-of-conduct/
Mozilla COC guide: https://mozillascience.github.io/working-open-workshop/code_of_conduct/

**Comment by vbhv** [comment]
I think the COC from Community Covenant for the website is a good COC to build off from. https://community-covenant.net/version/1/0/
For contributor I suggest this https://www.contributor-covenant.org/ It can be included in github/other repositories.
@Erioldoesdesign

**Comment by vbhv** [comment]
Example from http://dev.to

All participants of The DEV Community are expected to abide by our Code of Conduct, both online and during in-person events that are hosted and/or associated with DEV.

Our Pledge
In the interest of fostering an open and welcoming environment, we as moderators of DEV pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.
Our Standards
Examples of behavior that contributes to creating a positive environment include:
* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Referring to people by their preferred pronouns and using gender-neutral pronouns when uncertain
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members
Examples of unacceptable behavior by participants include:
* The use of sexualized language or imagery and unwelcome sexual attention or advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or electronic address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a professional setting
* Dismissing or attacking inclusion-oriented requests
We pledge to prioritize marginalized people’s safety over privileged people’s comfort. We will not act on complaints regarding:
* ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
* Reasonable communication of boundaries, such as 'leave me alone,' 'go away,' or 'I’m not discussing this with you.'
* Someone’s refusal to explain or debate social justice concepts
* Criticisms of racist, sexist, cissexist, or otherwise oppressive behavior or assumptions
Enforcement
Violations of the Code of Conduct may be reported by contacting the team via the abuse report form or by sending an email to yo@dev.to. All reports will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. Further details of specific enforcement policies may be posted separately.
Moderators have the right and responsibility to remove comments or other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any members for other behaviors that they deem inappropriate, threatening, offensive, or harmful.
Attribution
This Code of Conduct is adapted from:
* Contributor Covenant, version 1.4
* Write/Speak/Code
* Geek Feminism

**Comment by Erioldoesdesign** [comment]
Looking good @vbhv examples are good ones to build from :)

**Comment by vbhv** [comment]
Added two versions. One for community and the other for contributor

Community CoC
https://docs.google.com/document/d/1cgFy5eKe67YSb-NnghNAyyxK8pdT9yFe0a9lJ8EwSzg/

Contributor CoC
https://docs.google.com/document/d/1WjHofPDWkaeV5UYbKHhoZCuNT7Oc5nwG2eBkdmUPDz0/

@Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
@klickass @thomaskueber

**Comment by rowasc** [comment]
This CoC looks good. I'd probably like to see us add an anonymous form of reporting _and_ specific folks who you can escalate to if a member of the team acts in an inappropriate manner, to ensure folks feel safe reporting on _us_ too. -this applies to Ushahidi CoC as well IMO-
ie: email "coc@ushahidi.com" which is read by X,Y,Z person , or to X,Y,or Z if you feel more comfortable doing that.

**Comment by klickass** [comment]
Both look good to me

**Comment by Erioldoesdesign** [comment]
Added these as a .md file to the repo so they can be pulled and iterated on if need be

Noting that I haven't addressed Romina's suggestion of an anon form. Will create  and new ticket to create via google forms and add to CoC
